apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-harbor-contactpoint
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contactpoints.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: telegram-harbor
        receivers:
          - uid: telegram-harbor-receiver
            type: telegram
            settings:
              bottoken: "8897845260:AAGmoaDV87xi4J6Ad8Aq5jAEjSyrhj6tIAw"
              chatid: "6400347307"
              message: |
                {{ `{{ len .Alerts.Firing }}` }} alerta(s) en {{ `{{ .CommonLabels.namespace }}` }}
                {{ `{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}` }}
